name = "list"   # 使用期望的名称，避免警告
compatibility_date = "2026-02-15"
main = "workers.js"

kv_namespaces = [
  { binding = "DEVICE_INFO", id = "3bc37191711e4344b54a96f75b7ce0e2" },
  { binding = "BAN_LIST", id = "e162fdfb4e664dc4a741f8e3aa30afcd" }
]

[vars]
ADMIN_AUTH_KEY = "你的超级密钥"

[observability]
[observability.logs]
enabled = true
invocation_logs = true
